services:
    web:
        container_name: book-store
        image: ghcr.io/gaareth/svelte-books:latest
        ports:
            - 4000:3000 # to:from
        env_file:
            - .env.production # see env.example for the required keys
        volumes:
            - book-store:/database
            - book-store:/uploads
        restart: unless-stopped
volumes:
    book-store:
        name: book-store
