services:
    web:
        container_name: book-store-dev
        build: .
        ports:
            - 3000:3000 # to:from
        env_file:
            - .env.production # see env.example for the required keys
        volumes:
            - book-store:/database
            - book-store:/uploads
volumes:
    book-store:
