name: NodeJS check

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 24

            - name: Install pnpm
              run: npm install -g pnpm@11.22.0

            - name: Install deps
              run: pnpm install --frozen-lockfile

            - name: svelte check
              run: pnpm run check-noenv

            # - name: eslint
            #   run: pnpm run lint

            - name: vite build
              run: pnpm run build-noenv
